name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: mkdir -p build/bin/ && go build -v -o build/bin/templating-device cmd/templating-device.go

    - name: Test
      run: go test -v cmd/templating-device.go cmd/templating-device_test.go
